version: "3.9"

services: 

    rabbitmq:
        container_name: 'rabbitmq'
        image: rabbitmq:3.8-management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
    
        
    events:
          container_name: myevents
          restart: always
          build: ./events
          ports:
              - "5003:3000"
          links:
              - eventsmongo
              - rabbitmq
              - consul 

    tickets:
          container_name: mytickets
          restart: always
          build: ./tickets
          ports:
              - "5002:3000"
          links:
              - ticketsmongo
              - rabbitmq
              - consul
    eventsmongo:
          container_name: eventsmongo
          image: mongo 
          ports:
              - "27018:27017"

    ticketsmongo:
          container_name: ticketsmongo
          image: mongo 
          ports:
              - "27019:27017"

    consul:

        image: consul:latest
        ports:
            - "8400:8400"
            - "8500:8500"
            - "8600:8600"
            - "8600:8600/udp"
        command: "agent -server -bootstrap-expect=1 -ui -client 0.0.0.0"

  
    caddy:
        image: caddy:2.4.3-alpine
        volumes:
            - ./caddy/Caddyfile:/home/caddy/Caddyfile
        command: "caddy run --config /home/caddy/Caddyfile"
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - events
            - tickets

